### ISSUE TITLE
TODO: Decoupling process

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/rust-crypto-decoupled#1]
- [x] AES
- [x] ECB, CBC, and CTR block cipher modes
- [ ] Fortuna
- [x] HMAC
- [x] PBKDF2
- [x] PKCS padding for CBC block cipher mode
- [x] Scrypt
- [x] Bcrypt
- [x] Blake2
- [x] Blowfish
- [x] ChaCha20
- [x] ChaCha20 + Poly1305 AEAD
- [x] Curve25519
- [x] Ed25519
- [x] Ghash
- [x] HC128
- [x] MD5
- [x] Poly1305
- [x] RC4
- [x] RIPEMD-160
- [x] Salsa20 and XSalsa20
- [x] Sha1
- [x] Sha2
- [x] Sha3
- [x] Sosemanuk
- [x] Whirlpool

By files:
- [x] aes.rs
- [ ] aes_gcm.rs
- [x] aesni.rs
- [x] aesni_helpers.asm
- [x] aesni_helpers.c
- [x] aessafe.rs
- [ ] bcrypt_pbkdf.rs
- [x] blockmodes.rs (no_std)
- [ ] fortuna.rs
- [x] hkdf.rs
- [x] pbkdf2.rs
- [x] scrypt.rs
- [x] aead.rs
- [x] bcrypt.rs
- [x] blake2b.rs
- [x] blake2s.rs
- [x] blowfish.rs
- [x] buffer.rs
- [x] chacha20.rs
- [x] chacha20poly1305.rs
- [x] cryptoutil.rs
- [x] curve25519.rs
- [x] digest.rs
- [x] ed25519.rs
- [x] ghash.rs
- [x] hc128.rs
- [x] hmac.rs (no_std)
- [x] lib.rs
- [x] mac.rs
- [x] md5.rs
- [x] poly1305.rs
- [x] rc4.rs
- [x] ripemd160.rs
- [x] salsa20.rs
- [x] sha1.rs
- [x] sha2.rs
- [x] sha3.rs
- [x] simd.rs
- [x] sosemanuk.rs 
- [x] step_by.rs
- [x] symmetriccipher.rs
- [x] util.rs
- [x] util_helpers.asm
- [x] util_helpers.c
- [x] whirlpool.rs
